name = "gyro-error-calculator"
main = "src/worker.ts"
compatibility_date = "2024-11-01"

[build]
command = "pnpm install --frozen-lockfile && pnpm run build:cf"

[assets]
directory = "out"
binding = "ASSETS"

# 配置自定義域名路由
routes = [
    { pattern = "6156150.xyz/gyro-error-calculator", zone_name = "6156150.xyz" },
    { pattern = "6156150.xyz/gyro-error-calculator/*", zone_name = "6156150.xyz" }
]
